package com.lucaslopez.LedgerX.domain.logActivitys;

public enum TipoAccion {
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    REGISTRO_USUARIO,
    TRANSFERENCIA_REALIZADA,
    DEPOSITO_REALIZADO,
    RETIRO_REALIZADO,
    CONSULTA_SALDO,
    CAMBIO_PERFIL_REALIZADO,
    CUENTA_SUSPENDIDA
}
