spring.application.name=LedgerX

spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.data.mongodb.uri=mongodb://${MONGO_HOST}:27017/${MONGO_DB}

server.error.include-stacktrace=never

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

api.security.secret=${JWT_SECRET}

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# Configuracion de Formato de Fechas
# Elimina la notacion cientifica/timestamps y usa String
spring.jackson.serialization.write-dates-as-timestamps=false

# Formato: Dia-Mes-anio Hora:Minuto:Segundo
spring.jackson.date-format=dd-MM-yyyy HH:mm:ss

# Zona horaria
spring.jackson.time-zone=America/Argentina/Buenos_Aires